package main

import (
	"fmt"
	"maps"
	"os"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/dave/jennifer/jen"

	"github.com/octopusdeploy/kubernetes-monitor/internal/config"
)

type flag struct {
	Name    string
	Default any
	Usage   string
	Type    reflect.Type
}

// genflags generates Go code that defines flag setters for the configuration flags defined in the config package.
// It reads the tags from the config types and generates a struct with methods to initialize flags for each section.
func main() {
	// Get the output file from command line arguments
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "Usage: genflags <output file>")
		os.Exit(1)
	}
	out := os.Args[1]

	// Bootstep the code generation by creating a new Jennifer file
	f := jen.NewFile("config")
	f.HeaderComment("Code generated by cmd/genflags; DO NOT EDIT.")
	f.ImportName("github.com/spf13/pflag", "pflag")
	f.ImportName("time", "time")

	// Iterate over the flag sections defined in the config package, in a stable
	// order so that regenerating produces byte-identical output.
	flagSections := getFlagSections()
	for _, section := range slices.Sorted(maps.Keys(flagSections)) {
		flags := flagSections[section]

		// Create the implementation of the FlagSetter interface
		sectionName := strings.ToUpper(section[:1]) + section[1:]
		structName := sectionName + "FlagSetter"
		varName := strings.ToLower(section[:1]) + section[1:] + "FlagSetter"

		f.Type().Id(structName).Struct(
			jen.Id("flagSet").Op("*").Add(jen.Qual("github.com/spf13/pflag", "FlagSet")),
		)

		// Create the InitFlags receiver method for the implementation
		f.Func().
			Params(jen.Id("s").Add(jen.Id(structName))).
			Id("InitFlags").
			Params().
			BlockFunc(func(g *jen.Group) {
				for _, fl := range flags {
					call := g.Id("s").Dot("flagSet")
					switch fl.Type.Kind() {
					case reflect.String:
						call.Dot("String").Call(
							jen.Lit(fl.Name),
							jen.Lit(fl.Default.(string)),
							jen.Lit(fl.Usage),
						)
					case reflect.Bool:
						def, _ := strconv.ParseBool(fl.Default.(string))
						call.Dot("Bool").Call(
							jen.Lit(fl.Name),
							jen.Lit(def),
							jen.Lit(fl.Usage),
						)
					case reflect.Int:
						ival, _ := strconv.Atoi(fl.Default.(string))
						call.Dot("Int").Call(
							jen.Lit(fl.Name),
							jen.Lit(ival),
							jen.Lit(fl.Usage),
						)
					// Handle int64 as a special case for durations
					case reflect.Int64:
						d, err := time.ParseDuration(fl.Default.(string))
						if err != nil {
							panic(fmt.Sprintf("failed to parse duration for flag %s: %v", fl.Name, err))
						}
						call.Dot("Duration").Call(
							jen.Lit(fl.Name),
							jen.Lit(d.Seconds()).Op("*").Qual("time", "Second"),
							jen.Lit(fl.Usage),
						)
					case reflect.Slice:
						if fl.Type.Elem().Kind() == reflect.String {
							call.Dot("StringSlice").Call(
								jen.Lit(fl.Name),
								jen.Nil(),
								jen.Lit(fl.Usage),
							)
						} else {
							panic(
								fmt.Sprintf(
									"unhandled slice element type %s for flag %s",
									fl.Type.Elem().Kind(),
									fl.Name,
								),
							)
						}
					default:
						panic("unhandled default case")
					}
				}
			})

		// Add a newline for readability
		f.Line()

		// Create the InitFlags convenience function
		f.Func().Id("Init"+sectionName+"Flags").
			Params(jen.Id("flagSet").Op("*").Add(jen.Qual("github.com/spf13/pflag", "FlagSet"))).
			Block(
				jen.Id(varName).Op(":=").Id(structName).Values(jen.Id("flagSet")),
				jen.Id(varName).Dot("InitFlags").Call(),
			)
	}

	if err := f.Save(out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func collectEmbeddedTypes(t reflect.Type) []reflect.Type {
	if t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t.Kind() != reflect.Struct {
		return nil
	}

	var embeddedTypes []reflect.Type
	for i := 0; i < t.NumField(); i++ {
		sf := t.Field(i)
		if sf.Anonymous {
			embeddedTypes = append(embeddedTypes, sf.Type)
			types := collectEmbeddedTypes(sf.Type)
			embeddedTypes = append(embeddedTypes, types...)
		}
	}
	return embeddedTypes
}

func getFlagSections() map[string][]flag {
	flagSections := map[string][]flag{}
	cfgType := reflect.TypeOf(config.Config{})
	cfgChildren := collectEmbeddedTypes(cfgType)
	for _, t := range cfgChildren {
		for _, field := range reflect.VisibleFields(t) {
			name := strings.Split(field.Tag.Get("mapstructure"), ",")[0]
			if name == "" {
				continue
			}
			def := field.Tag.Get("default")
			usage := field.Tag.Get("usage")
			section := field.Tag.Get("section")

			flagSections[section] = append(flagSections[section], flag{
				Name:    name,
				Default: def,
				Usage:   usage,
				Type:    field.Type,
			})
		}
	}
	return flagSections
}
