package cluster

import v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

func getDefaultApiResources() map[v1.TypeMeta]bool {
	return map[v1.TypeMeta]bool{
		{APIVersion: "v1", Kind: "Binding"}:                                                       true,
		{APIVersion: "v1", Kind: "ComponentStatus"}:                                               false,
		{APIVersion: "v1", Kind: "ConfigMap"}:                                                     true,
		{APIVersion: "v1", Kind: "Endpoints"}:                                                     true,
		{APIVersion: "v1", Kind: "Event"}:                                                         true,
		{APIVersion: "v1", Kind: "LimitRange"}:                                                    true,
		{APIVersion: "v1", Kind: "Namespace"}:                                                     false,
		{APIVersion: "v1", Kind: "Node"}:                                                          false,
		{APIVersion: "v1", Kind: "PersistentVolumeClaim"}:                                         true,
		{APIVersion: "v1", Kind: "PersistentVolume"}:                                              false,
		{APIVersion: "v1", Kind: "Pod"}:                                                           true,
		{APIVersion: "v1", Kind: "PodTemplate"}:                                                   true,
		{APIVersion: "v1", Kind: "ReplicationController"}:                                         true,
		{APIVersion: "v1", Kind: "ResourceQuota"}:                                                 true,
		{APIVersion: "v1", Kind: "Secret"}:                                                        true,
		{APIVersion: "v1", Kind: "ServiceAccount"}:                                                true,
		{APIVersion: "v1", Kind: "Service"}:                                                       true,
		{APIVersion: "admissionregistration.k8s.io/v1", Kind: "MutatingWebhookConfiguration"}:     false,
		{APIVersion: "admissionregistration.k8s.io/v1", Kind: "ValidatingAdmissionPolicy"}:        false,
		{APIVersion: "admissionregistration.k8s.io/v1", Kind: "ValidatingAdmissionPolicyBinding"}: false,
		{APIVersion: "admissionregistration.k8s.io/v1", Kind: "ValidatingWebhookConfiguration"}:   false,
		{APIVersion: "apiextensions.k8s.io/v1", Kind: "CustomResourceDefinition"}:                 false,
		{APIVersion: "apiregistration.k8s.io/v1", Kind: "APIService"}:                             false,
		{APIVersion: "apps/v1", Kind: "ControllerRevision"}:                                       true,
		{APIVersion: "apps/v1", Kind: "DaemonSet"}:                                                true,
		{APIVersion: "apps/v1", Kind: "Deployment"}:                                               true,
		{APIVersion: "apps/v1", Kind: "ReplicaSet"}:                                               true,
		{APIVersion: "apps/v1", Kind: "StatefulSet"}:                                              true,
		{APIVersion: "authentication.k8s.io/v1", Kind: "SelfSubjectReview"}:                       false,
		{APIVersion: "authentication.k8s.io/v1", Kind: "TokenReview"}:                             false,
		{APIVersion: "authorization.k8s.io/v1", Kind: "LocalSubjectAccessReview"}:                 true,
		{APIVersion: "authorization.k8s.io/v1", Kind: "SelfSubjectAccessReview"}:                  false,
		{APIVersion: "authorization.k8s.io/v1", Kind: "SelfSubjectRulesReview"}:                   false,
		{APIVersion: "authorization.k8s.io/v1", Kind: "SubjectAccessReview"}:                      false,
		{APIVersion: "autoscaling/v2", Kind: "HorizontalPodAutoscaler"}:                           true,
		{APIVersion: "batch/v1", Kind: "CronJob"}:                                                 true,
		{APIVersion: "batch/v1", Kind: "Job"}:                                                     true,
		{APIVersion: "certificates.k8s.io/v1", Kind: "CertificateSigningRequest"}:                 false,
		{APIVersion: "coordination.k8s.io/v1", Kind: "Lease"}:                                     true,
		{APIVersion: "discovery.k8s.io/v1", Kind: "EndpointSlice"}:                                true,
		{APIVersion: "events.k8s.io/v1", Kind: "Event"}:                                           true,
		{APIVersion: "flowcontrol.apiserver.k8s.io/v1", Kind: "FlowSchema"}:                       false,
		{APIVersion: "flowcontrol.apiserver.k8s.io/v1", Kind: "PriorityLevelConfiguration"}:       false,
		{APIVersion: "helm.cattle.io/v1", Kind: "HelmChartConfig"}:                                true,
		{APIVersion: "helm.cattle.io/v1", Kind: "HelmChart"}:                                      true,
		{APIVersion: "k3s.cattle.io/v1", Kind: "Addon"}:                                           true,
		{APIVersion: "k3s.cattle.io/v1", Kind: "ETCDSnapshotFile"}:                                false,
		{APIVersion: "metrics.k8s.io/v1beta1", Kind: "NodeMetrics"}:                               false,
		{APIVersion: "metrics.k8s.io/v1beta1", Kind: "PodMetrics"}:                                true,
		{APIVersion: "networking.k8s.io/v1", Kind: "IngressClass"}:                                false,
		{APIVersion: "networking.k8s.io/v1", Kind: "Ingress"}:                                     true,
		{APIVersion: "networking.k8s.io/v1", Kind: "NetworkPolicy"}:                               true,
		{APIVersion: "node.k8s.io/v1", Kind: "RuntimeClass"}:                                      false,
		{APIVersion: "policy/v1", Kind: "PodDisruptionBudget"}:                                    true,
		{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "ClusterRoleBinding"}:                  false,
		{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "ClusterRole"}:                         false,
		{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "RoleBinding"}:                         true,
		{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "Role"}:                                true,
		{APIVersion: "scheduling.k8s.io/v1", Kind: "PriorityClass"}:                               false,
		{APIVersion: "storage.k8s.io/v1", Kind: "CSIDriver"}:                                      false,
		{APIVersion: "storage.k8s.io/v1", Kind: "CSINode"}:                                        false,
		{APIVersion: "storage.k8s.io/v1", Kind: "CSIStorageCapacity"}:                             true,
		{APIVersion: "storage.k8s.io/v1", Kind: "StorageClass"}:                                   false,
		{APIVersion: "storage.k8s.io/v1", Kind: "VolumeAttach}ent"}:                               false,
	}
}
