{{- if not .Values.registration.register -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-monitor.authentication.secretName"  . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubernetes-monitor.labels" . | nindent 4 }}
type: Opaque
data:
  INSTALLATION_ID: {{ required "When installing without automatically registering, .Values.monitor.installationId must be specified" .Values.monitor.installationId | b64enc }}
  AUTHENTICATION_TOKEN: {{ required "When installing without automatically registering, .Values.monitor.authenticationToken must be specified" .Values.monitor.authenticationToken | b64enc }}
{{- end }}