{{- if and .Values.registration.register (not .Values.registration.serverAccessTokenSecretName) (or .Values.registration.serverAccessToken .Values.registration.serverApiUrl) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-monitor.registration.secretName"  . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubernetes-monitor.labels" . | nindent 4 }}
  annotations:
    {{- include "kubernetes-monitor.registration.hookAnnotations" . | nindent 4 }}
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  SERVER_ACCESS_TOKEN: {{ required "When registering the monitor automatically, registration.serverAccessToken must be provided." .Values.registration.serverAccessToken | b64enc }}
{{- end }}