{{- if and .Values.registration.register .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-monitor.registration.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubernetes-monitor.labels" . | nindent 4 }}
  annotations:
    {{- include "kubernetes-monitor.registration.hookAnnotations" . | nindent 4 }}
    "helm.sh/hook-weight": "-5"
    {{- with .Values.registration.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.registration.serviceAccount.automountServiceAccountToken }}
{{- end }}