// Code generated by cmd/genflags; DO NOT EDIT.

package config

import (
	"github.com/spf13/pflag"
	"time"
)

type CommonFlagSetter struct {
	flagSet *pflag.FlagSet
}

func (s CommonFlagSetter) InitFlags() {
	s.flagSet.String("server-grpc-url", "", "Address of the gRPC server e.g. grpc://my.server.app:8443")
	s.flagSet.String("installation-id", "", "ID used to uniquely identify this installation")
	s.flagSet.String("authentication-token", "", "Authentication token used for gRPC requests")
	s.flagSet.String("config-path", "", "Directory to store configuration files")
	s.flagSet.String("config-store", "file", "Method of storing authentication secrets.\n  - file\n  - kubernetes\n Default: file")
	s.flagSet.String("kubernetes-store-prefix", "", "Prefix for the Kubernetes store objects when using kubernetes store")
	s.flagSet.String("kubernetes-store-namespace", "", "Namespace for the Kubernetes store objects when using kubernetes store")
	s.flagSet.String("ca-certificate-path", "", "Absolute path to the CA certificate file used to verify the server's gRPC certificate.")
	s.flagSet.Bool("use-kubeconfig", false, "Use kubectl config client instead of in-cluster client")
	s.flagSet.String("kubeconfig-path", "", "Absolute path to the kubeconfig file")
	s.flagSet.Bool("debug", false, "Enables debug mode, including logging and continuous profiling")
	s.flagSet.Bool("tracing", false, "Enable tracing for the monitor. This will enable the default HTTP tracer to http://localhost:4318. You can set the OTEL_EXPORTER_OTLP_ENDPOINT environment variable to control the endpoint used.")
	s.flagSet.Bool("print-traces", false, "Enable stdout trace printing for the monitor. This requires tracing to be enabled. This will stop the monitor from sending traces via HTTP.")
	s.flagSet.String("pyroscope-url", "", "URL of the Pyroscope server to send profiling data to")
}

func InitCommonFlags(flagSet *pflag.FlagSet) {
	commonFlagSetter := CommonFlagSetter{flagSet}
	commonFlagSetter.InitFlags()
}

type RegisterFlagSetter struct {
	flagSet *pflag.FlagSet
}

func (s RegisterFlagSetter) InitFlags() {
	s.flagSet.String("server-api-url", "", "Address of the server API eg. https://my.server.app")
	s.flagSet.String("server-access-token", "", "Access token for the server API, used to register the monitor with the server")
	s.flagSet.String("machine-name", "", "Name of the Kubernetes agent that the monitor is tied to")
	s.flagSet.String("space-id", "", "ID of the space where the agent will be registered with the server")
}

func InitRegisterFlags(flagSet *pflag.FlagSet) {
	registerFlagSetter := RegisterFlagSetter{flagSet}
	registerFlagSetter.InitFlags()
}

type RunFlagSetter struct {
	flagSet *pflag.FlagSet
}

func (s RunFlagSetter) InitFlags() {
	s.flagSet.Bool("pin-grpc-certificate", false, "Pin the gRPC server certificate to only trust the thumbprint obtained during registration. Will not validate against any CAs.")
	s.flagSet.Duration("monitor-period", 300.0*time.Second, "Send a complete snapshot of monitored resources to the server every period. Default: 5 minutes")
	s.flagSet.Int("max-grpc-send-message-size-bytes", 52428800, "Largest gRPC message the monitor will send, in bytes. This limit applies to the compressed size. Default: 50MiB")
	s.flagSet.Int("max-grpc-receive-message-size-bytes", 20971520, "Largest gRPC message the monitor will accept, in bytes. This limit applies to the decompressed size. Default: 20MiB")
	s.flagSet.Bool("disable-grpc-compression", false, "Send gRPC messages uncompressed. Only use for troubleshooting.")
	s.flagSet.Duration("health-check-interval", 30.0*time.Second, "Send a gRPC health check to Octopus Server at this interval. Set to 0 to disable, which should only be for troubleshooting (error-recovery is limited when health checks are disabled). Default: 30 seconds")
	s.flagSet.Duration("health-check-give-up-after", 300.0*time.Second, "Exit once Octopus Server has gone unanswered for this long, so the pod is restarted. Default: 5 minutes")
	s.flagSet.String("server-thumbprint", "", "Thumbprint of the gRPC server certificate")
	s.flagSet.StringSlice("target-namespaces", nil, "Comma-separated list of namespaces to monitor. When set, the monitor only watches these namespaces instead of cluster-wide.")
	s.flagSet.Bool("cluster-scoped-resources", false, "Include cluster-scoped resources (Nodes, Namespaces, PVs, etc.) in monitoring. Only effective when target-namespaces is set.")
}

func InitRunFlags(flagSet *pflag.FlagSet) {
	runFlagSetter := RunFlagSetter{flagSet}
	runFlagSetter.InitFlags()
}
